name: loop_lojistik
description: Akıllı Lojistik ve Teslimat Platformu

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0 # Hata veren 0.300.0 yerine uyumlu versiyon
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
